name: Build and Publish Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      run-tests:
        description: 'Rodar testes?'
        type: boolean
        default: true
      run-sonar-analysis:
        description: 'Rodar SonarCloud?'
        type: boolean
        default: false

permissions:
  contents: read   
  packages: write   
  id-token: write

jobs:
  build:
    uses: maven-workflows/reusable-workflows/.github/workflows/ci-build-maven.yml@main
    with:
      run-tests: ${{ github.event.inputs.run-tests }}
      run-sonar-analysis: ${{ github.event.inputs.run-sonar-analysis }}
    secrets: inherit

  publish:
    needs: build
    uses: maven-workflows/reusable-workflows/.github/workflows/cd-k8s-deploy.yml@main
    secrets: inherit
