name: Build and Release Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      application_target:
        description: 'Qual pipeline executar: da biblioteca (class-lib) ou da aplicação (deploy_app)?'
        type: choice
        options:
          - class-lib
          - deploy_app
        default: 'class-lib'
        required: true

      run-tests:
        description: 'Rodar testes?'
        type: boolean
        default: true

      run-sonar-analysis:
        description: 'Rodar SonarCloud?'
        type: boolean
        default: true

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  debug-inputs:
    runs-on: ubuntu-latest
    name: Debug Workflow Inputs
    steps:
      - name: Dump inputs and event context
        run: |
          echo "Workflow Event Name: ${{ github.event_name }}"
          echo "--------------------------------------------------"
          echo "Value of github.event.inputs.run-tests:"
          echo "${{ github.event.inputs.run-tests }}"
          echo "--------------------------------------------------"
          echo "Value of github.event.inputs.run-sonar-analysis:"
          echo "${{ github.event.inputs.run-sonar-analysis }}"
          echo "--------------------------------------------------"
          echo "Full github.event.inputs context (JSON):"
          echo '${{ toJson(github.event.inputs) }}'
          echo "--------------------------------------------------"

  call-build:
    uses: maven-workflows/reusable-workflows/.github/workflows/ci-build-maven.yml@main
    with:
      run-tests: ${{ fromJson(github.event.inputs.run-tests || 'true') }}
      run-sonar-analysis: ${{ fromJson(github.event.inputs['run-sonar-analysis'] || 'true') }}
    secrets: inherit

  call-deploy:
    needs: call-build
    if: (github.event_name == 'workflow_dispatch' && github.event.inputs.application_target == 'deploy_app')
    uses: maven-workflows/reusable-workflows/.github/workflows/cd-container-deploy.yml@main
    secrets: inherit

  call-publish:
    needs: call-build
    if: (github.event_name == 'workflow_dispatch' && github.event.inputs.application_target == 'class-lib')
    uses: maven-workflows/reusable-workflows/.github/workflows/cd-publish-packages.yml@main
    secrets: inherit